language: cpp
env:
  - ARCH=x64
  - ARCH=arm
compiler: gcc
addons:
  apt:
    sources:
    - mysql-5.7-trusty
    packages:
    - libmysql++-dev:i386
    - gcc-multilib
    - g++-multilib
git:
  depth: false
notifications:
  email: false
script:
  - bash -ex .travis-ci.sh
after_success:
  - mkdir accounts logs save scripts
  - mv spheresvr spheresvr-arm
  - tar -czvf SphereSvr-Arm32.tar.gz accounts/ logs/ save/ scripts/ spheresvr-arm -C src/ sphere.ini sphereCrypt.ini
  - curl -T SphereSvr-Arm32.tar.gz -u $FTP_USER:$FTP_PASSWORD $FTP_SERVER
